# Generated by Django 5.1.4 on 2025-02-20 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('gateway_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Serial Number')),
                ('name', models.CharField(max_length=50)),
                ('gateway_logo', models.ImageField(upload_to='payment_gateway_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantPaymentGateway',
            fields=[
                ('gateway_payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Serial Number')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(limit_choices_to={'role': 'merchant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentgateway')),
            ],
        ),
    ]
