# Generated by Django 5.1.4 on 2025-02-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportmessage',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
