# Generated by Django 5.1.4 on 2025-02-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_created_at_supportmessage_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sn',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterModelTable(
            name='supportmessage',
            table='support_messages',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='support_tickets',
        ),
    ]
