# Generated by Django 5.1.4 on 2025-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=50),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
