# Generated by Django 5.1.4 on 2025-02-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='sn',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Serial Number'),
        ),
    ]
