# Generated by Django 5.1.4 on 2025-02-14 13:39

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='password_hash',
            field=models.CharField(default='', help_text='Merchant Password Hash', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='password_salt',
            field=models.CharField(default='', help_text='Password Salt for security', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_name',
            field=models.CharField(help_text='Merchant Business Name', max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(help_text='Merchant Email Address', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='first_name',
            field=models.CharField(default='', help_text='Merchant First Name', max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='last_name',
            field=models.CharField(help_text='Merchant Last Name', max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Merchant ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Merchant Middle Name (Optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
