# Generated by Django 5.1.4 on 2025-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_merchant_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
