# Generated by Django 5.1.4 on 2025-02-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_merchant_password_hash_merchant_password_salt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='password_salt',
        ),
    ]
