# Generated by Django 5.1.4 on 2025-02-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merchant_is_active_merchant_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_admin',
        ),
    ]
