# Generated by Django 5.1.4 on 2025-02-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_merchant_options_alter_merchant_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='total_balance',
        ),
    ]
