# Generated by Django 5.1.4 on 2025-02-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_merchant_is_active_remove_merchant_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='password_salt',
        ),
    ]
