# Generated by Django 5.1.4 on 2025-02-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_merchant_total_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'default_related_name': 'merchants', 'permissions': [('manage_balance', 'Can manage merchant balance')]},
        ),
    ]
