# Generated by Django 5.1.4 on 2025-02-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_merchant_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merchant',
            table='merchant',
        ),
    ]
