# Generated by Django 5.1.4 on 2025-02-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_merchant_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'default_related_name': 'merchants', 'permissions': [('manage_balance', 'Can manage merchant balance'), ('verify_kyc', 'Can verify merchant KYC details'), ('manage_orders', 'Can manage merchant orders'), ('manage_wallets', 'Can manage merchant wallets'), ('manage_transactions', 'Can manage merchant transactions'), ('manage_merchants', 'Can manage other merchants')]},
        ),
    ]
