# Generated by Django 5.1.4 on 2025-02-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_merchant_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merchant',
            table='merchants',
        ),
    ]
